# This is a basic workflow to help you get started with Actions

name: Build Image

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Update Env
        run: |
            apt update
    
      - name: Fetch Repo
        run: |
            git clone https://github.com/armbian/build
            cd build

      - name: Build
        run: |
            ./compile.sh build \
            BOARD=pocketchip-sd \
            BRANCH=current \
            BUILD_DESKTOP=yes \
            BUILD_MINIMAL=no \
            DESKTOP_ENVIRONMENT=xfce \
            DESKTOP_ENVIRONMENT_CONFIG_NAME=config_base \
            KERNEL_CONFIGURE=no \
            RELEASE=noble \
            EXPERT=YES \
            KERNEL_COMPILER=clang
